### ISSUE TITLE
请问MHXX NS版的汉化补丁的问题

### ISSUE THREAD

**Issue by bournejason** [dnasdw/game_patches#1]
看到1.50版本的汉化补丁说需要安装nsp，请问有没有不安装nsp的汉化方式呢？谢谢！

**Comment by dnasdw** [comment]
如果不安装nsp，想办法更新到1.5.0也是可以的，否则1.5.0更新补丁内的部分文件应该无法通过LayeredFS覆盖本体，主要还是exefs部分应该覆盖不全。

**Comment by bournejason** [comment]
正版卡带，联网更新到最新，然后把相应的文件放到SD:/atmosphere/contents/[titleID]/是不是在CFW sysnand里就可以直接使用汉化了呢？
多谢及时回答！

**Comment by dnasdw** [comment]
理论应该是，也得看看最新版本是否是1.5.0版了，这补丁都至少4年了。

**Comment by bournejason** [comment]
是的，不过应该版本还是这个，我回头试试看，谢啦

**Comment by dnasdw** [comment]
好的，先试试吧。

**Comment by bournejason** [comment]
没问题，可以用
